### PR TITLE
Audio integration

### PR DESCRIPTION
**Pull request by VitorCantao**

### CODE REVIEW

**Comment by jvcanavarro** [comment]
image
Does this glitch also appear on the audio editing screen for you?

**Comment by jvcanavarro** [comment]
image
After canceling audio title edition :(

**Comment by VitorCantao** [comment]
@jvcanavarro It doesn't. What are the steps to reproduce?

Also, did you try erasing the data?

**Comment by jvcanavarro** [comment]
This glitch only occurs immediately after uploading the audio, when I try to edit other times it doesn't happen, strange.

**Comment by jvcanavarro** [comment]
> @jvcanavarro It doesn't. What are the steps to reproduce?
> 
> Also, did you try erasing the data?

Steps to reproduce:
> Create text and go to detail page
> 'Add Recording'
> Select a sample
> Click on edit icon and open phone keyboard (the glitchs only appears after keyboard is visible)
> Cancel edition, then open audio card again (no glitches).

I'll try to erase app cache now

**Comment by VitorCantao** [comment]
> > @jvcanavarro It doesn't. What are the steps to reproduce?
> > Also, did you try erasing the data?
> 
> Steps to reproduce:
> 
> > Create text and go to detail page
> > 'Add Recording'
> > Select a sample
> > Click on edit icon and open phone keyboard (the glitchs only appears after keyboard is visible)
> > Cancel edition, then open audio card again (no glitches).
> 
> I'll try to erase app cache now

Yeah, I'm seeing it. Weird bug

**Review by jvcanavarro — APPROVED** [review]

**Pull request merged**
