### PR TITLE
Upload Audio

### PR DESCRIPTION
**Pull request by jvcanavarro**

### CODE REVIEW

**Comment by jvcanavarro** [comment]
Folks, please test the file manager on your devices/emulators.

**Comment by VitorCantao** [comment]
A test failed, just need to change `classId` to `studentId`

**Review by VitorCantao — CHANGES_REQUESTED** [review]
When doing the following, there's an untreated exception:

* Add a new audio
* Click on edit
* Click to select audio
* Then press back

**Comment by jvcanavarro** [comment]
This is caused because the file is saved in the database as soon as it is uploaded. I will switch tomorrow to a "temporary file" that is only saved after confirmation.

**Review by VitorCantao — APPROVED** [review]

**Pull request merged**
