### PR TITLE
Add travis file

### PR DESCRIPTION
**Pull request by renan-cunha**
Please, accept the travis CI file

### CODE REVIEW

**Review by VitorCantao — CHANGES_REQUESTED** [review]
I _believe_ we have to add some additional configuration:

https://itnext.io/configuring-travis-ci-and-coveralls-with-flutter-4c65edfc42d3

**Comment by renan-cunha** [comment]
this command ```./flutter/bin/flutter test``` will run even if the project is in ```mobile```?

**Comment by VitorCantao** [comment]
> this command `./flutter/bin/flutter test` will run even if the project is in `mobile`?

I think this command is not related to the project, but to the flutter files in the system

**Review by VitorCantao — APPROVED** [review]
Everything is working now

**Pull request merged**
